config/routes.rb
Rails.application.routes.draw do
  get 'ordem_servico/index'
  get 'ordem_servico/show'
  get 'equipe/index'
  get 'equipe/show'
  get 'veiculos/index'
  get 'veiculos/show'
  get 'home/index'
  get 'home/show'
  get 'mecanicos/index', to: 'mecanicos#index'
  get 'clientes/index'
  get 'pecas/index'
  get 'login/index'
  get 'login/esqueceu_senha'
  post 'login/esqueceu_senha'
  get 'login/trocar_senha'
  put 'login/trocar_senha'
  get 'pecas/new', to: 'pecas#new'
  post 'pecas/adicionar_peca', to: 'pecas#adicionar_peca'
  get 'clientes/new', to: 'clientes#new'
  post 'clientes/adicionar_cliente', to: 'clientes#adicionar_cliente'
  get 'mecanicos/new', to: 'mecanicos#new'
  get 'mecanicos/adicionar_mecanico', to: 'mecanicos#adicionar_mecanico'
  post 'mecanicos/adicionar_mecanico', to: 'mecanicos#adicionar_mecanico'
  post 'veiculos/create', to: 'veiculos#create'
  post 'veiculos/adicionar_veiculo', to: 'veiculos#adicionar_veiculo'
  post 'equipe/create', to: 'equipe#create'
  post 'equipe/adicionar_equipe', to: 'equipe#adicionar_equipe'
  post 'ordens_servico/create', to: 'ordens_servico#create'
  get 'login/perfil', to: 'login#perfil', as: 'perfil'
  get 'login/edit_perfil', to: 'login#atualizar_perfil', as: 'edit_perfil'
  post 'login/logout', to: 'login#logout', as: 'logout'
  resources :veiculos
  resources :pecas
  resources :clientes
  resources :mecanicos
  resources :home
  resources :equipe
  resources :ordens_servico
  # devise_for :admins
  #get 'boas_vinda/index'
  resources :admins #Cria as rotas para o controller admins GET, POST, PUT, DELETE
  get "up" => "rails/health#show", as: :rails_health_check
  get 'login/index'
  post 'login/login'
  get 'login/logout'
  root 'home#index'
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  validates :Nome, presence: true
  validates :Email, presence: true
  validates :CPF, presence: true
  validates :Telefone, presence: true
  validates :Endereco, presence: true
  validates :Nome, length: { minimum: 3 }
  validates :Email, length: { minimum: 3 }
  validates :CPF, length: { minimum: 3 }
  validates :Telefone, length: { minimum: 3 }
  validates :Endereco, length: { minimum: 3 }
  validates :CPF, numericality: { greater_than: 0 }
  validates :Telefone, numericality: { greater_than: 0 }
  validates :CPF, numericality: { only_integer: true }
  validates :Telefone, numericality: { only_integer: true }
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:edit, :update, :destroy, :show]

  def index
    @clientes = Cliente.new
  end

  def new
    @cliente = Cliente.new
  end

  def show
  end

  #ADICIONAR CLIENTE
  def adicionar_cliente
    @cliente = Cliente.new(cliente_par)
      if @cliente.save
        flash[:notice] = "Cliente adicionado com sucesso"
        redirect_to '/'
      else
        flash[:notice] = "Erro ao adicionar cliente"
        redirect_to '/clientes/index'
      end
      rescue StandardError => e
        flash[:notice] = "Erro ao adicionar cliente"
        redirect_to '/clientes/index'
  end

  #DELETE CLIENTE
  def destroy
    @cliente.destroy!
      respond_to do |format|
        format.html { redirect_to '/', notice: "Cliente cancelado com sucesso..." }
        format.json { head :no_content }
    end
  end

  # PATCH/PUT
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url, notice: "Cliente editado com sucesso..." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def cliente_params
    params.require(:cliente).permit(:Nome, :CPF, :Email, :Telefone, :Endereco)
  end

  def set_cliente
    @cliente = Cliente.find_by(params[:idClientes])
  end

  #Parametros para adicionar um cliente...
  def cliente_par
    params.permit(:Nome, :CPF, :Email, :Telefone, :Endereco)
  end

end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_cliente.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Adicionar Peça</title>
        <link rel="shortcut icon" href="/images/favicon_32x32.png">
        <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 d-flex container-info">
        <div class="Detalhes-cliente d-flex">
          <div class="item">
            <strong class="Label"><i class="bi bi-person-fill"></i> Nome</strong>
            <p class="fw-bold"><%= cliente.Nome %></p>
          </div>

          <div class="item">
            <strong class="Label"><i class="bi bi-envelope"></i> Email</strong>
            <p><%= cliente.Email %></p>
          </div>

          <div class="item">
            <strong class="Label"><i class="bi bi-card-heading"></i> CPF</strong>
            <p><%= cliente.CPF %></p>
          </div>

          <div class="item">
            <strong class="Label"><i class="bi bi-telephone"></i> Telefone</strong>
            <p><%= cliente.Telefone %></p>
          </div>

          <div class="item">
            <strong class="Label"><i class="bi bi-geo-alt"></i> Endereço</strong>
            <p><%= cliente.Endereco %></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/clientes/_form.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Editar Mecânico</title>
        <link rel="shortcut icon" href="/images/favicon_32x32.png">
        <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
<body>
  <div class="container d-flex">
    <%= form_with(model: cliente, class: "container") do |form| %>
      <div class="row">
        <div class="col-sm-12 d-flex field-login">
          <div class="form-group form-add">
            <%= form.label :Nome, "Nome", class: "form-label" %>
            <%= form.text_field :Nome, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= form.label :Email, "Email", class: "form-label" %>
            <%= form.text_field :Email, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= form.label :CPF, "CPF", class: "form-label" %>
            <%= form.text_field :CPF, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= form.label :Telefone, "Telefone", class: "form-label" %>
            <%= form.text_field :Telefone, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= form.label :Endereco, "Endereço", class: "form-label" %>
            <%= form.text_field :Endereco, class: "form-control" %>
          </div>

          <div class="actions">
            <%= form.submit "Confirmar", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="alert-danger mt-2">
    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
      <script>
        setTimeout(function() {
          document.querySelector('.notice-login').style.display = 'none';
            }, 3000);
      </script>
    <% end %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/clientes/edit.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Adicionar Peça</title>
        <link rel="shortcut icon" href="/images/favicon_32x32.png">
        <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
<body>
      <nav class="navbar navbar-expand-lg nav-dash sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><i class="bi bi-gear-wide-connected"></i> Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/ordens_servico"><i class="bi bi-plus-circle"></i> Adicionar OS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/mecanicos"><i class="bi bi-plus-circle"></i> Adicionar mecânicos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/login/perfil"><i class="bi bi-person-circle"></i> Perfil</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Mais opções
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/pecas"><i class="bi bi-plus-circle"></i> Adicionar peças</a></li>
                            <li><a class="dropdown-item" href="/clientes"><i class="bi bi-plus-circle"></i> Adicionar clientes</i></a></li>
                             <li><a class="dropdown-item" href="/veiculos"><i class="bi bi-plus-circle"></i> Adicionar veiculos</a></li>
                             <li><a class="dropdown-item" href="/equipe"><i class="bi bi-plus-circle"></i> Adicionar equipes</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-12 d-flex card-title mt-4 mb-4">
                <%= link_to "Voltar", cliente_path(@cliente) %>
                <h3 class="text-center"><i class="bi bi-pencil-square"></i> Editando Cliente</h3>
            </div>
        </div>
    </div>

    <%= render "form", cliente: @cliente %>

    <br>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/clientes/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Adicionar Clientes</title>
        <link rel="shortcut icon" href="/images/favicon_32x32.png">
        <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
<body>
    <nav class="navbar navbar-expand-lg nav-dash sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><i class="bi bi-gear-wide-connected"></i> Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/ordens_servico"><i class="bi bi-plus-circle"></i> Adicionar OS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/mecanicos"><i class="bi bi-plus-circle"></i> Adicionar mecânicos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/login/perfil"><i class="bi bi-person-circle"></i> Perfil</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Mais opções
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/pecas"><i class="bi bi-plus-circle"></i> Adicionar peças</a></li>
                            <li><a class="dropdown-item" href="/clientes"><i class="bi bi-plus-circle"></i> Adicionar clientes</i></a></li>
                             <li><a class="dropdown-item" href="/veiculos"><i class="bi bi-plus-circle"></i> Adicionar veiculos</a></li>
                             <li><a class="dropdown-item" href="/equipe"><i class="bi bi-plus-circle"></i> Adicionar equipes</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <%= form_tag '/clientes/adicionar_cliente', class: "container", method: :post do %>
        <div class="row">
            <div class="col-sm-12 d-flex card-title mt-4 mb-4">
                <%= link_to "Voltar", root_path %>
                <h3><i class="bi bi-person-plus-fill"></i> Adicionando um cliente</h3>
            </div>
            <div class="col-sm-12 d-flex field-login mb-5">
                <div class="form-group form-add">
                    <%= label_tag :Nome, "Nome", class: "form-label" %>
                    <%= text_field_tag :Nome, nil, class: "form-control" %>
                </div>

                <div class="form-group form-add">
                    <%= label_tag :Email, "Email", class: "form-label" %>
                    <%= text_field_tag :Email, nil, class: "form-control" %>
                </div>

                <div class="form-group form-add">
                    <%= label_tag :CPF, "CPF", class: "form-label" %>
                    <%= number_field_tag :CPF, nil, class: "form-control" %>
                </div>

                <div class="form-group form-add">
                    <%= label_tag :Telefone, "Telefone", class: "form-label" %>
                    <%= text_field_tag :Telefone, nil, class: "form-control" %>
                </div>

                <div class="form-group form-add">
                    <%= label_tag :Endereco, "Endereço", class: "form-label" %>
                    <%= text_field_tag :Endereco, nil, class: "form-control" %>
                </div>

                <div class="actions">
                    <%= submit_tag 'Confirmar', class: 'btn btn-primary' %>
                </div>
            </div>
        </div>
        <div class="alert-danger mt-2">
            <% if flash[:notice] %>
                <p class="notice-login"><%= flash[:notice] %></p>
                <script>
                    setTimeout(function() {
                      document.querySelector('.notice-login').style.display = 'none';
                    }, 3000);
                </script>
            <% end %>
        </div>
        <% end %>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/clientes/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cliente</title>
    <link rel="shortcut icon" href="/images/favicon_32x32.png">
    <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg nav-dash sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><i class="bi bi-gear-wide-connected"></i> Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/ordens_servico"><i class="bi bi-plus-circle"></i> Adicionar OS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/mecanicos"><i class="bi bi-plus-circle"></i> Adicionar mecânicos</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Mais opções
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/pecas"><i class="bi bi-plus-circle"></i> Adicionar peças</a></li>
                            <li><a class="dropdown-item" href="/clientes"><i class="bi bi-plus-circle"></i> Adicionar clientes</i></a></li>
                             <li><a class="dropdown-item" href="/veiculos"><i class="bi bi-plus-circle"></i> Adicionar veiculos</a></li>
                             <li><a class="dropdown-item" href="/equipe"><i class="bi bi-plus-circle"></i> Adicionar equipes</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-12 d-flex card-title mt-4 mb-4">
                <%= link_to "Voltar", root_path %>
                <h3><i class="bi bi-people"></i> Clientes de qualidade VIP</h3>
            </div>
        </div>
    </div>
 
    <%= render @cliente %>

    <div class="btn-can-put d-flex justify-center">
        <%= button_to "Cancelar cliente", @cliente, method: :delete, data: { controller: 'sweetalert', action: 'click->sweetalert#showAlert', sweetalert_target: 'sweetalert'}, class: "btn btn-danger" %>
        <%= link_to "Atualizar cliente", edit_cliente_path(@cliente), class: "btn btn-success" %>
    </div>

    <div class="alert-danger mt-2">
        <% if flash[:notice] %>
            <p class="notice-login"><%= flash[:notice] %></p>
            <script>
                setTimeout(function() {
                  document.querySelector('.notice-login').style.display = 'none';
                }, 3000);
            </script>
        <% end %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>