config/routes.rb
Rails.application.routes.draw do
  get 'ordem_servico/index'
  get 'ordem_servico/show'
  get 'equipe/index'
  get 'equipe/show'
  get 'veiculos/index'
  get 'veiculos/show'
  get 'home/index'
  get 'home/show'
  get 'mecanicos/index', to: 'mecanicos#index'
  get 'clientes/index'
  get 'pecas/index'
  get 'login/index'
  get 'login/esqueceu_senha'
  post 'login/esqueceu_senha'
  get 'login/trocar_senha'
  put 'login/trocar_senha'
  get 'pecas/new', to: 'pecas#new'
  post 'pecas/adicionar_peca', to: 'pecas#adicionar_peca'
  get 'clientes/new', to: 'clientes#new'
  post 'clientes/adicionar_cliente', to: 'clientes#adicionar_cliente'
  get 'mecanicos/new', to: 'mecanicos#new'
  get 'mecanicos/adicionar_mecanico', to: 'mecanicos#adicionar_mecanico'
  post 'mecanicos/adicionar_mecanico', to: 'mecanicos#adicionar_mecanico'
  post 'veiculos/create', to: 'veiculos#create'
  post 'veiculos/adicionar_veiculo', to: 'veiculos#adicionar_veiculo'
  post 'equipe/create', to: 'equipe#create'
  post 'equipe/adicionar_equipe', to: 'equipe#adicionar_equipe'
  post 'ordens_servico/create', to: 'ordens_servico#create'
  get 'login/perfil', to: 'login#perfil', as: 'perfil'
  get 'login/edit_perfil', to: 'login#atualizar_perfil', as: 'edit_perfil'
  post 'login/logout', to: 'login#logout', as: 'logout'
  resources :veiculos
  resources :pecas
  resources :clientes
  resources :mecanicos
  resources :home
  resources :equipe
  resources :ordens_servico
  # devise_for :admins
  #get 'boas_vinda/index'
  resources :admins #Cria as rotas para o controller admins GET, POST, PUT, DELETE
  get "up" => "rails/health#show", as: :rails_health_check
  get 'login/index'
  post 'login/login'
  get 'login/logout'
  root 'home#index'
end

app/models/peca.rb
class Peca < ApplicationRecord
  has_and_belongs_to_many :ordens_servico
  validates :Tipo_peca, presence: true
  validates :Valor_peca, presence: true
  validates :Quantidade, presence: true
  validates :Tipo_peca, length: { minimum: 3 }
  validates :Valor_peca, numericality: { greater_than: 0 }
  validates :Quantidade, numericality: { greater_than: 0 }
  validates :Quantidade, numericality: { only_integer: true }
end

app/controllers/pecas_controller.rb
class PecasController < ApplicationController
  before_action :set_peca, only: %i[edit update destroy show]
  def index
    @peca = Peca.new
  end

  def new
    @peca = Peca.new
  end

  def show
  end

  def edit
  end

  #ADICIONAR
  def adicionar_peca
    @peca = Peca.new(peca_par)
    if @peca.save
      flash[:notice] = "Peça criada com sucesso"
      redirect_to '/'
    else
      flash[:notice] = "Erro ao criar peça"
      redirect_to '/pecas'
    end
    rescue StandardError => e
      flash[:notice] = "Erro ao criar peça"
      redirect_to '/pecas'
  end

  #DELETE
  def destroy
    @peca.destroy!
      respond_to do |format|
      format.html { redirect_to '/', notice: "Peça cancelada com sucesso..." }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /admins/1
  def update
    respond_to do |format|
      if @peca.update(peca_params)
        format.html { redirect_to peca_url(@peca), notice: "Peça editada com sucesso..." }
        format.json { render :show, status: :ok, location: @peca }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @peca.errors, status: :unprocessable_entity }
        #flash[:notice] = "Erro ao editar a peça..."
      end
    end
  end

  private

  def peca_params
    params.require(:peca).permit(:Tipo_peca, :Quantidade, :Valor_peca)
  end

  def set_peca
    @peca = Peca.find(params[:id])
  end

  #Parametros para adicionar uma peça nova...
  def peca_par
    params.permit(:Tipo_peca, :Quantidade, :Valor_peca)
  end
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/views/pecas/_form.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Adicionar Peça</title>
        <link rel="shortcut icon" href="/images/favicon_32x32.png">
        <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
<body>  
  <div class="container d-flex">
    <%= form_with(model: peca, class: "container") do |form| %>
      <div class="row">
        <div class="col-sm-12 d-flex field-login">
          <div class="form-group form-add">
            <%= form.label :Tipo_peca, class: "form-label" %>
            <%= form.text_field :Tipo_peca, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= form.label :Quantidade, class: "form-label" %>
            <%= form.number_field :Quantidade, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= form.label :Valor_peca, class: "form-label" %>
            <%= form.number_field :Valor_peca, cass: "form-control" %>
          </div>

          <div class="actions">
            <%= form.submit "Confirmar", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
      <% if peca.errors.any? %>
        <div style="color: red">
          <p>Houve algum erro...</p>
        </div>
      <% end %>
    <% end %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/pecas/_peca.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Peça</title>
        <link rel="shortcut icon" href="/images/favicon_32x32.png">
        <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
<body>
   <div class="container">
    <div class="row">
      <div class="col-lg-12 d-flex container-info">
        <div class="Detalhes-cliente d-flex">
          <div class="item">
            <strong class="Label"><i class="bi bi-wrench-adjustable-circle"></i> Tipo de peça</strong>
            <p><%= peca.Tipo_peca %></p>
          </div>

          <div class="item">
            <strong class="Label"><i class="bi bi-archive"></i> Quantidade</strong>
            <p><%= peca.Quantidade %></p>
          </div>

          <div class="item">
            <strong class="Label"><i class="bi bi-currency-dollar"></i> Valor da peça</strong>
            <p><%= peca.Valor_peca %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/pecas/edit.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Adicionar Peça</title>
        <link rel="shortcut icon" href="/images/favicon_32x32.png">
        <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
<body>
      <nav class="navbar navbar-expand-lg nav-dash sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><i class="bi bi-gear-wide-connected"></i> Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/ordens_servico"><i class="bi bi-plus-circle"></i> Adicionar OS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/mecanicos"><i class="bi bi-plus-circle"></i> Adicionar mecânicos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/login/perfil"><i class="bi bi-person-circle"></i> Perfil</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Mais opções
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/pecas"><i class="bi bi-plus-circle"></i> Adicionar peças</a></li>
                            <li><a class="dropdown-item" href="/clientes"><i class="bi bi-plus-circle"></i> Adicionar clientes</i></a></li>
                             <li><a class="dropdown-item" href="/veiculos"><i class="bi bi-plus-circle"></i> Adicionar veiculos</a></li>
                             <li><a class="dropdown-item" href="/equipe"><i class="bi bi-plus-circle"></i> Adicionar equipes</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-12 d-flex card-title mt-4 mb-4">
                <%= link_to "Voltar", peca_path(@peca) %>
                <h3 class="text-center"><i class="bi bi-pencil-square"></i> Editando Peça</h3>
            </div>
        </div>
    </div>

  <%= render "form", peca: @peca %>

  <br>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/pecas/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Adicionar Peça</title>
        <link rel="shortcut icon" href="/images/favicon_32x32.png">
        <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
<body>
    <nav class="navbar navbar-expand-lg nav-dash sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><i class="bi bi-gear-wide-connected"></i> Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/ordens_servico"><i class="bi bi-plus-circle"></i> Adicionar OS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/mecanicos"><i class="bi bi-plus-circle"></i> Adicionar mecânicos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/login/perfil"><i class="bi bi-person-circle"></i> Perfil</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Mais opções
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/pecas"><i class="bi bi-plus-circle"></i> Adicionar peças</a></li>
                            <li><a class="dropdown-item" href="/clientes"><i class="bi bi-plus-circle"></i> Adicionar clientes</i></a></li>
                             <li><a class="dropdown-item" href="/veiculos"><i class="bi bi-plus-circle"></i> Adicionar veiculos</a></li>
                             <li><a class="dropdown-item" href="/equipe"><i class="bi bi-plus-circle"></i> Adicionar equipes</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <%= form_tag '/pecas/adicionar_peca', class: "container", method: :post do %>
        <div class="row">
            <div class="col-sm-12 d-flex card-title mt-4 mb-4">
                <%= link_to "Voltar", root_path %>
                <h3><i class="bi bi-person-plus-fill"></i> Peças de qualidade VIP</h3>
            </div>
            <div class="col-sm-12 d-flex field-login mb-5">
                <div class="form-group form-add">
                    <%= label_tag :Tipo_peca,"Tipo da peça", class: "form-label" %>
                    <%= text_field_tag :Tipo_peca, nil, class: "form-control" %>
                </div>

                <div class="form-group form-add">
                    <%= label_tag :Quantidade,"Quantidade", class: "form-label" %>
                    <%= number_field_tag :Quantidade, nil, class: "form-control" %>
                </div>

                <div class="form-group form-add">
                    <%= label_tag :Valor_peca,"Valor peça", class: "form-label" %>
                    <%= number_field_tag :Valor_peca, nil, class: "form-control" %>
                </div>

                <div class="actions">
                    <%= submit_tag 'Confirmar', class: 'btn btn-primary' %>
                </div>
            </div>
        </div>
        <div class="alert-danger mt-2">
            <% if flash[:notice] %>
                <p class="notice-login"><%= flash[:notice] %></p>
                <script>
                    setTimeout(function() {
                      document.querySelector('.notice-login').style.display = 'none';
                    }, 3000);
                </script>
            <% end %>
        </div>
        <% end %>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/pecas/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Peça</title>
    <link rel="shortcut icon" href="/images/favicon_32x32.png">
    <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg nav-dash sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><i class="bi bi-gear-wide-connected"></i> Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/ordens_servico"><i class="bi bi-plus-circle"></i> Adicionar OS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/mecanicos"><i class="bi bi-plus-circle"></i> Adicionar mecânicos</a>
                    </li>
                    <li class="nav-item dropdown">
                    <li class="nav-item">
                        <a class="nav-link" href="/login/perfil"><i class="bi bi-person-circle"></i> Perfil</a>
                    </li>
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Mais opções
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/pecas"><i class="bi bi-plus-circle"></i> Adicionar peças</a></li>
                            <li><a class="dropdown-item" href="/clientes"><i class="bi bi-plus-circle"></i> Adicionar clientes</i></a></li>
                             <li><a class="dropdown-item" href="/veiculos"><i class="bi bi-plus-circle"></i> Adicionar veiculos</a></li>
                             <li><a class="dropdown-item" href="/equipe"><i class="bi bi-plus-circle"></i> Adicionar equipes</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-12 d-flex card-title mt-4 mb-4">
                <%= link_to "Voltar", root_path %>
                <h3><i class="bi bi-wrench-adjustable-circle"></i> Peças de qualidade VIP</h3>
            </div>
        </div>
    </div>

    <%= render @peca %>

    <div class="btn-can-put d-flex justify-center">
        <%= button_to "Cancelar peça", @peca, method: :delete,data: { controller: 'sweetalert', action: 'click->sweetalert#showAlert', sweetalert_target: 'sweetalert'}, class: "btn btn-danger" %>
        <%= link_to "Atualizar peça", edit_peca_path(@peca), class: "btn btn-success" %>
    </div>

    <div class="alert-danger mt-2">
        <% if flash[:notice] %>
            <p class="notice-login"><%= flash[:notice] %></p>
            <script>
                setTimeout(function() {
                  document.querySelector('.notice-login').style.display = 'none';
                }, 3000);
            </script>
        <% end %>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>