config/routes.rb
Rails.application.routes.draw do
  get 'ordem_servico/index'
  get 'ordem_servico/show'
  get 'equipe/index'
  get 'equipe/show'
  get 'veiculos/index'
  get 'veiculos/show'
  get 'home/index'
  get 'home/show'
  get 'mecanicos/index', to: 'mecanicos#index'
  get 'clientes/index'
  get 'pecas/index'
  get 'login/index'
  get 'login/esqueceu_senha'
  post 'login/esqueceu_senha'
  get 'login/trocar_senha'
  put 'login/trocar_senha'
  get 'pecas/new', to: 'pecas#new'
  post 'pecas/adicionar_peca', to: 'pecas#adicionar_peca'
  get 'clientes/new', to: 'clientes#new'
  post 'clientes/adicionar_cliente', to: 'clientes#adicionar_cliente'
  get 'mecanicos/new', to: 'mecanicos#new'
  get 'mecanicos/adicionar_mecanico', to: 'mecanicos#adicionar_mecanico'
  post 'mecanicos/adicionar_mecanico', to: 'mecanicos#adicionar_mecanico'
  post 'veiculos/create', to: 'veiculos#create'
  post 'veiculos/adicionar_veiculo', to: 'veiculos#adicionar_veiculo'
  post 'equipe/create', to: 'equipe#create'
  post 'equipe/adicionar_equipe', to: 'equipe#adicionar_equipe'
  post 'ordens_servico/create', to: 'ordens_servico#create'
  get 'login/perfil', to: 'login#perfil', as: 'perfil'
  get 'login/edit_perfil', to: 'login#atualizar_perfil', as: 'edit_perfil'
  post 'login/logout', to: 'login#logout', as: 'logout'
  resources :veiculos
  resources :pecas
  resources :clientes
  resources :mecanicos
  resources :home
  resources :equipe
  resources :ordens_servico
  # devise_for :admins
  #get 'boas_vinda/index'
  resources :admins #Cria as rotas para o controller admins GET, POST, PUT, DELETE
  get "up" => "rails/health#show", as: :rails_health_check
  get 'login/index'
  post 'login/login'
  get 'login/logout'
  root 'home#index'
end

app/models/equipe.rb
class Equipe < ApplicationRecord
  has_and_belongs_to_many :mecanicos, join_table: 'mecanicos_equipes'
  validates :Nome, presence: true
  validates :Descricao, presence: true
  validates :Especialidade, presence: true
end

app/controllers/equipe_controller.rb
class EquipeController < ApplicationController
  before_action :set_equipe, only: %i[edit update destroy show]

  def index
    @equipe = Equipe.all
    @mecanicos = Mecanico.all
  end

  def show
  end

  def edit
  end

  def new
    @equipe = Equipe.new
    @mecanicos = Mecanico.all
  end

  # ADICIONAR EQUIPE
  def adicionar_equipe
    @equipe = Equipe.new(equipe_par)

    if @equipe.save
      flash[:notice] = "Equipe adicionada com sucesso"
      redirect_to '/'
    else
      flash[:notice] = @equipe.errors.full_messages.join(", ")
      redirect_to '/equipe'
    end
    rescue StandardError => e
    flash[:notice] = "Erro ao adicionar equipe"
    redirect_to '/equipe'
  end

  # UPDATE EQUIPE
  def update
    respond_to do |format|
      if @equipe.update(equipe_par)
        format.html { redirect_to equipe_url(@equipe), notice: "Equipe editada com sucesso..." }
        format.json { render :show, status: :ok, location: @equipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETAR EQUIPE
  def destroy
    @equipe.destroy!
    respond_to do |format|
      format.html { redirect_to '/', notice: "Equipe cancelada com sucesso..." }
      format.json { head :no_content }
    end
  end

  private

  def equipe_par
    params.require(:equipe).permit(:Nome, :Descricao, :Especialidade, mecanico_ids: [])
  end

  def set_equipe
    @equipe = Equipe.find(params[:id])
  end
end

app/helpers/equipe_helper.rb
module EquipeHelper
end

app/views/equipe/_equipe.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Adicionar Peça</title>
        <link rel="shortcut icon" href="/images/favicon_32x32.png">
        <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 d-flex container-info">
        <div class="Detalhes-cliente d-flex">
          <div class="item">
            <strong class="Label"><i class="bi bi-aspect-ratio"></i> Nome</strong>
            <p><%= equipe.Nome %></p>
          </div>
          <div class="item">
            <strong class="Label"><i class="bi bi-aspect-ratio"></i> Descrição</strong>
            <p><%= equipe.Descricao %></p>
          </div>

          <div class="item">
            <strong class="Label"><i class="bi bi-speedometer"></i> Especialidade</strong>
            <p><%= equipe.Especialidade %></p>
          </div>

          <div class="item">
            <strong class="Label"><i class="bi bi-person-gear"></i> Mecânicos</strong>
            <ul>
              <% @equipe.mecanicos.each do |mecanico| %>
                <p><%= mecanico.Nome %><p>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/equipe/_form.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Equipe</title>
    <link rel="shortcut icon" href="/images/favicon_32x32.png">
    <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="container d-flex">
        <%= form_with(model:@equipe, local: true, class: "container") do |form| %>
        <div class="row">
        <div class="col-sm-12 d-flex field-login">
          <div class="form-group form-add">
            <%= form.label :Nome,"Nome", class: "form-label" %>
            <%= form.text_field :Nome, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= form.label :Descricao,"Descrição", class: "form-label" %>
            <%= form.text_area :Descricao, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= form.label :Especialidade,"Modelo", class: "form-label" %>
            <%= form.text_field :Especialidade, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= form.label :Mecanicos, "Mecanicos", class: "form-label"%>
            <%= form.collection_select :mecanico_ids, Mecanico.all, :idMecanicos, :Nome, { multiple: true }, { class: "form-control selecionador"}%>
          </div>

          <div class="actions">
            <%= form.submit "Confirmar", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
       <% end %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/equipe/edit.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Adicionar Peça</title>
        <link rel="shortcut icon" href="/images/favicon_32x32.png">
        <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
<body>
    <nav class="navbar navbar-expand-lg nav-dash sticky-top">
      <div class="container-fluid">
          <a class="navbar-brand" href="/"><i class="bi bi-gear-wide-connected"></i> Dashboard</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="/ordens_servico"><i class="bi bi-plus-circle"></i> Adicionar OS</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/mecanicos"><i class="bi bi-plus-circle"></i> Adicionar mecânicos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/login/perfil"><i class="bi bi-person-circle"></i> Perfil</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Mais opções
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="/pecas"><i class="bi bi-plus-circle"></i> Adicionar peças</a></li>
                    <li><a class="dropdown-item" href="/clientes"><i class="bi bi-plus-circle"></i> Adicionar clientes</i></a></li>
                    <li><a class="dropdown-item" href="/veiculos"><i class="bi bi-plus-circle"></i> Adicionar veiculos</a></li>
                    <li><a class="dropdown-item" href="/equipe"><i class="bi bi-plus-circle"></i> Adicionar equipes</a></li>
                  </ul>
                </li>
              </ul>
          </div>
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-12 d-flex card-title mt-4 mb-4">
                <%= link_to "Voltar", equipe_path(@equipe) %>
                <h3 class="text-center"><i class="bi bi-people-fill"></i> Editando Equipe</h3>
            </div>
        </div>
    </div>

    <%= render "form", cliente: @cliente %>

    <br>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/equipe/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Adicionar Equipe</title>
  <link rel="shortcut icon" href="/images/favicon_32x32.png">
  <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg nav-dash sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><i class="bi bi-gear-wide-connected"></i> Dashboard</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/ordens_servico"><i class="bi bi-plus-circle"></i> Adicionar OS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/mecanicos"><i class="bi bi-plus-circle"></i> Adicionar mecânicos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login/perfil"><i class="bi bi-person-circle"></i> Perfil</a>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Mais opções
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="/pecas"><i class="bi bi-plus-circle"></i> Adicionar peças</a></li>
              <li><a class="dropdown-item" href="/clientes"><i class="bi bi-plus-circle"></i> Adicionar clientes</i></a></li>
               <li><a class="dropdown-item" href="/veiculos"><i class="bi bi-plus-circle"></i> Adicionar veiculos</a></li>
               <li><a class="dropdown-item" href="/equipe"><i class="bi bi-plus-circle"></i> Adicionar equipes</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    <div class="container">
      <%= form_tag '/equipe/adicionar_equipe', class: "container", method: :post do %>
      <div class="row">
        <div class="col-sm-12 d-flex card-title mt-4 mb-4">
          <%= link_to "Voltar", root_path %>
          <h3><i class="bi bi-people"></i> Equipes de qualidade VIP</h3>
        </div>
        <div class="col-sm-12 d-flex field-login mb-5">
          <div class="form-group form-add">
            <%= label_tag :Nome,"Nome", class: "form-label" %>
            <%= text_field_tag 'equipe[Nome]', nil, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= label_tag :Especialidade,"Especialidade", class: "form-label" %>
            <%= text_field_tag 'equipe[Especialidade]', nil, class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= label_tag :Descricao,"Descrição", class: "form-label" %>
            <%= text_area_tag 'equipe[Descricao]', nil,class: "form-control" %>
          </div>

          <div class="form-group form-add">
            <%= label_tag 'equipe[mecanico_ids][]', "Mecânicos", class: "form-label" %>
            <%= select_tag 'equipe[mecanico_ids][]', options_from_collection_for_select(@mecanicos, 'id', 'Nome'), { multiple: true, class: "form-control selecionador" } %>
          </div>

          <div class="actions">
            <%= submit_tag 'Confirmar', class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
      <div class="alert-danger mt-2">
        <% if flash[:notice] %>
          <p class="notice-login"><%= flash[:notice] %></p>
          <script>
            setTimeout(function() {
              document.querySelector('.notice-login').style.display = 'none';
            }, 3000);
          </script>
        <% end %>
      </div>
      <% end %>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/views/equipe/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Equipe</title>
    <link rel="shortcut icon" href="/images/favicon_32x32.png">
    <link rel="stylesheet" href="<%= asset_path('application.css') %>"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg nav-dash sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><i class="bi bi-gear-wide-connected"></i> Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/ordens_servico"><i class="bi bi-plus-circle"></i> Adicionar OS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/mecanicos"><i class="bi bi-plus-circle"></i> Adicionar mecânicos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/login/perfil"><i class="bi bi-person-circle"></i> Perfil</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Mais opções
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/pecas"><i class="bi bi-plus-circle"></i> Adicionar peças</a></li>
                            <li><a class="dropdown-item" href="/clientes"><i class="bi bi-plus-circle"></i> Adicionar clientes</i></a></li>
                             <li><a class="dropdown-item" href="/veiculos"><i class="bi bi-plus-circle"></i> Adicionar veiculos</a></li>
                             <li><a class="dropdown-item" href="/equipe"><i class="bi bi-plus-circle"></i> Adicionar equipes</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-12 d-flex card-title mt-4 mb-4">
                <%= link_to "Voltar", root_path %>
                <h3><i class="bi bi-people-fill"></i> Equipes de qualidade VIP</h3>
            </div>
        </div>
    </div>

    <%= render partial: 'equipe', locals: { equipe: @equipe } %>

    <div class="btn-can-put d-flex justify-center">
        <%= button_to "Cancelar equipe", @equipe, method: :delete, data: { controller: 'sweetalert', action: 'click->sweetalert#showAlert', sweetalert_target: 'sweetalert'}, class: "btn btn-danger"  %>
        <%= link_to "Atualizar equipe", edit_equipe_path(@equipe), class: "btn btn-success" %>
    </div>

    <div class="alert-danger mt-2">
        <% if flash[:notice] %>
            <p class="notice-login"><%= flash[:notice] %></p>
            <script>
                setTimeout(function() {
                  document.querySelector('.noticlass: "btn btn-success"ce-login').style.display = 'none';
                }, 3000);
            </script>
        <% end %>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>